/* CREACION DE SP PARA INSERTAR PRODUCTOS EN LA BASE DE DATOS ORACLE SQL 19C */

CREATE OR REPLACE PROCEDURE sp_insert_product(
    IDPRODUCTO NUMBER,
    NOMBRE VARCHAR2,
    DESCRIPCION VARCHAR2,
    PRECIOUNITARIO NUMBER,
    CANTIDADSTOCK NUMBER,
    IDPROVEEDOR NUMBER,
    IDCATEGORIA NUMBER,
    IDSUBCATEGORIA NUMBER,  
    IDMARCA NUMBER,
    IDUNIDAD NUMBER)
IS
BEGIN
    INSERT INTO PRODUCTO (
    IDPRODUCTO, NOMBRE,DESCRIPCION, PRECIOUNITARIO, CANTIDADSTOCK, IDPROVEEDOR, IDCATEGORIA, IDSUBCATEGORIA, IDMARCA, IDUNIDAD)
    COMMIT;
END sp_insert_product;
