SELECT *
FROM TORNILLOS.CLIENTE
JOIN VENTA ON CLIENTE.IDCLIENTE = VENTA.IDCLIENTE
JOIN EMPLEADO ON EMPLEADO.IDEMPLEADO = VENTA.IDCLIENTE;


-- SECUANCIA PARA PRODUCTOS
CREATE SEQUENCE producto_seq START WITH 12 INCREMENT BY 1;

