SELECT *
FROM TORNILLOS.CLIENTE
JOIN VENTA ON CLIENTE.IDCLIENTE = VENTA.IDCLIENTE
JOIN EMPLEADO ON EMPLEADO.IDEMPLEADO = VENTA.IDCLIENTE;


-- SECUANCIA PARA PRODUCTOS

CREATE SEQUENCE producto_seq START WITH 12 INCREMENT BY 1;
CREATE SEQUENCE provider_seq START WITH 11 INCREMENT BY 1;
CREATE SEQUENCE customer_seq START WITH 11 INCREMENT BY 1;
CREATE SEQUENCE user_seq START WITH 11 INCREMENT BY 1;



SELECT *
FROM venta v
    JOIN USUARIO u on u.IDUSUARIO = v.IDUSUARIO
WHERE
    v.IDUSUARIO = 2

SELECT U.*
FROM
    DETALLECOMPRA D
    INNER JOIN COMPRA C ON C.IDCOMPRA = D.IDCOMPRA
    INNER JOIN USUARIO U ON U.IDUSUARIO = C.IDUSUARIO
WHERE
    U.IDUSUARIO = 1

SELECT * FROM PRODUCTO WHERE IDPRODUCTO = 10;

SELECT
    v.IDVENTA as VENTA,
    TO_CHAR(v.FECHA, 'DD/MM/YYYY') AS FECHA,
    c.NOMBRE AS CLIENTE,
    v.TOTAL AS TOTAL,
    u.NOMBRE AS VENDEDOR,
    m.NOMBRE AS METODO_PAGO
FROM
    TORNILLOS.VENTA v
    JOIN TORNILLOS.CLIENTE c ON v.IDCLIENTE = c.IDCLIENTE
    JOIN TORNILLOS.USUARIO u ON v.IDUSUARIO = u.IDUSUARIO
    LEFT JOIN (
        SELECT p.IDVENTA, MIN(p.IDPAGO) AS PRIMERPAGO
        FROM TORNILLOS.PAGOVENTA p
        GROUP BY
            p.IDVENTA
    ) pp ON v.IDVENTA = pp.IDVENTA
    LEFT JOIN TORNILLOS.PAGOVENTA p ON pp.PRIMERPAGO = p.IDPAGO
    LEFT JOIN TORNILLOS.METODOPAGO m ON p.IDMETODOPAGO = m.IDMETODO

-- resumen se la venta con jpa query
SELECT SUM(v.TOTAL) AS TOTAL
FROM
    TORNILLOS.VENTA v
    JOIN TORNILLOS.CLIENTE c ON v.IDCLIENTE = c.IDCLIENTE
    JOIN TORNILLOS.USUARIO u ON v.IDUSUARIO = u.IDUSUARIO
    LEFT JOIN (
        SELECT p.IDVENTA, MIN(p.IDPAGO) AS PRIMERPAGO
        FROM TORNILLOS.PAGOVENTA p
        GROUP BY
            p.IDVENTA
    ) pp ON v.IDVENTA = pp.IDVENTA
    LEFT JOIN TORNILLOS.PAGOVENTA p ON pp.PRIMERPAGO = p.IDPAGO
    LEFT JOIN TORNILLOS.METODOPAGO m ON p.IDMETODOPAGO = m.IDMETODO
ORDER BY v.FECHA

SELECT
    d.IDCOMPRA AS idCompra,
    pr.NOMBRE AS producto,
    d.CANTIDAD AS cantidad,
    d.COSTOUNITARIO AS precioUnitario,
    (d.CANTIDAD * d.COSTOUNITARIO) AS subtotal
FROM TORNILLOS.DETALLECOMPRA d
    JOIN TORNILLOS.PRODUCTO pr ON d.IDPRODUCTO = pr.IDPRODUCTO
WHERE
    d.IDCOMPRA = 1

SELECT
    c.IDCOMPRA AS COMPRA,
    TO_CHAR(c.FECHA, 'DD/MM/YYYY') AS FECHA,
    p.NOMBRE AS PROVEEDOR,
    c.TOTAL AS TOTAL,
    u.NOMBRE AS RESPONSABLE,
    COALESCE(m.NOMBRE, 'No pagado') AS METODOPAGO
FROM
    TORNILLOS.COMPRA c
    JOIN TORNILLOS.PROVEEDOR p ON c.IDPROVEEDOR = p.IDPROVEEDOR
    JOIN TORNILLOS.USUARIO u ON c.IDUSUARIO = u.IDUSUARIO
    LEFT JOIN (
        SELECT p.IDCOMPRA, MIN(p.IDPAGO) AS PRIMERPAGO
        FROM TORNILLOS.PAGOCOMPRA p
        GROUP BY
            p.IDCOMPRA
    ) pp ON c.IDCOMPRA = pp.IDCOMPRA
    LEFT JOIN TORNILLOS.PAGOCOMPRA pc ON pp.PRIMERPAGO = pc.IDPAGO
    LEFT JOIN TORNILLOS.METODOPAGO m ON pc.IDMETODOPAGO = m.IDMETODO
ORDER BY c.FECHA DESC

SELECT SUM(v.TOTAL) AS TOTAL
FROM
    TORNILLOS.VENTA v
    JOIN TORNILLOS.CLIENTE c ON v.IDCLIENTE = c.IDCLIENTE
    JOIN TORNILLOS.USUARIO u ON v.IDUSUARIO = u.IDUSUARIO
    LEFT JOIN (
        SELECT p.IDVENTA, MIN(p.IDPAGO) AS PRIMERPAGO
        FROM TORNILLOS.PAGOVENTA p
        GROUP BY
            p.IDVENTA
    ) pp ON v.IDVENTA = pp.IDVENTA
    LEFT JOIN TORNILLOS.PAGOVENTA p ON pp.PRIMERPAGO = p.IDPAGO
    LEFT JOIN TORNILLOS.METODOPAGO m ON p.IDMETODOPAGO = m.IDMETODO
WHERE
    v.FECHA = sysdate

SELECT SUM(CANTIDADSTOCK) AS STOCK_TOTAL FROM