


CREATE TABLESPACE CONTINGENCIA_TABLESPACE
DATAFILE '/opt/oracle/oradata/tablespace/contingencia01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TEMPORARY TABLESPACE CONTINGENCIA_TEMP
TEMPFILE '/opt/oracle/oradata/temp/contingencia_temp01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE USER CONTINGENCIA IDENTIFIED BY CONTINGENCIA
DEFAULT TABLESPACE CONTINGENCIA_TABLESPACE
TEMPORARY TABLESPACE CONTINGENCIA_TEMP;

GRANT CREATE SESSION TO CONTINGENCIA;
GRANT CONNECT, RESOURCE TO CONTINGENCIA;
GRANT UNLIMITED TABLESPACE TO CONTINGENCIA;
GRANT ALL PRIVILEGES TO CONTINGENCIA;

