
CREATE TABLESPACE TORNILLOS_TABLESPACE
DATAFILE '/opt/oracle/oradata/tablespace/tornillos01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TEMPORARY TABLESPACE TORNILLOS_TEMP
TEMPFILE '/opt/oracle/oradata/temp/tornillos_temp01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE USER TORNILLOS IDENTIFIED BY TORNILLOS
DEFAULT TABLESPACE TORNILLOS_TABLESPACE
TEMPORARY TABLESPACE TORNILLOS_TEMP;

GRANT ALL PRIVILEGES TO TORNILLOS;
GRANT CREATE SESSION TO TORNILLOS;





