#!/bin/bash
ORACLE_HOME=/opt/oracle/product/19c/dbhome_1
export ORACLE_HOME
export PATH=$ORACLE_HOME/bin:$PATH
export ORACLE_SID=ORCL

FECHA=$(date +"%Y%m%d")
DIR_BACKUP=/opt/oracle/oradata/BD_BACKUP
LOG_FILE=$DIR_BACKUP/rman_backup_$FECHA.log

rman target / log=$LOG_FILE <<EOF
RUN {
  ALLOCATE CHANNEL ch1 DEVICE TYPE DISK FORMAT '$DIR_BACKUP/full_%U.bkp';
  BACKUP DATABASE PLUS ARCHIVELOG;
  DELETE NOPROMPT OBSOLETE;
  DELETE NOPROMPT BACKUP COMPLETED BEFORE 'SYSDATE-7';
  RELEASE CHANNEL ch1;
}
EOF